# Generated by Django 5.0.11 on 2025-07-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='category',
            field=models.CharField(choices=[('Income', 'income'), ('Expense', 'expense')], default='-------', max_length=50),
        ),
    ]
