# Generated by Django 5.0.11 on 2025-07-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_alter_budgets_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgets',
            old_name='user_id',
            new_name='user',
        ),
    ]
